### ISSUE TITLE
Hook seed error

### ISSUE THREAD

**Issue by Seykhel** [antonbabenko/modules.tf-lambda#11]
##The dynamic update for the values don't work

The seeding of the dynamic value in the terraform.tfvars don't work. 
See the image below.

<img width="637" alt="Schermata 2019-05-03 alle 20 37 22" src="https://user-images.githubusercontent.com/8466042/57158508-e5af8580-6de3-11e9-9f86-6dec61e30a06.png">

**Comment by antonbabenko** [comment]
Hi Seykhel!

Thanks for opening this issue! For me, it means that you have at least tried this out! It really makes me a happier person and developer!

Closer to your point. I am aware that there are a bit too many dependencies to get the code generated by `modules.tf` to work. Last week I started working on [tfvars-annotations](https://github.com/antonbabenko/tfvars-annotations) - a tool which will process `terraform.tfvars` and update values based on annotations specified there. This will remove the need for `gnu-sed`, `jq` and `grep` (each of these has different versions on different platforms).

I expect to release https://github.com/antonbabenko/tfvars-annotations during next week and replace the buggy shell script during next week or two.

Meanwhile, you can get that script working if you install [gnu-sed](https://www.gnu.org/software/sed/) (`brew install gnu-sed` on Mac).

Don't hesitate if you have any other questions!

**Comment by Seykhel** [comment]
Hi Anton, I really appreciate your what you are doing. Thanks for the reply and good work.
