### ISSUE TITLE
Set folder names matching names of components on diagram

### ISSUE THREAD

**Issue by antonbabenko** [antonbabenko/modules.tf-lambda#22]
## Is your feature request related to a problem? Please describe.

Names of folders are confusing - rds_1, security-group_1...

## Describe the solution you'd like

Use names from components, replace strange characters with single `_`

## Additional context

![cloudcraft-proposal-naming](https://user-images.githubusercontent.com/393243/76458120-5814cd00-63da-11ea-94ad-548392f39dfb.png)

**Comment by antonbabenko** [comment]
@genaker This was way easier than I expected, fixed and deployed.

Thanks for the feedback!

**Comment by Genaker** [comment]
Thanks Grate Job!

**Comment by Genaker** [comment]
It can be an issue. I didn't try to run it but 

```
dependency "aws-data" {
  config_path = "../aws-data"
}

dependency "Production-VPC" {
  config_path = "../Production-VPC"
}

dependency "SSH22-SecurityGroup" {
  config_path = "../SSH22-SecurityGroup"
}

dependency "WebNode-LoadBalancer" {
  config_path = "../WebNode-LoadBalancer"
}

```
where folder actually is lowercased 

Possible solutions:
1. Lowercase this part of code generation also 

`  config_path = "../webnode-loadnalancer"`

2. Don't lowercase the names of the folders

**Comment by antonbabenko** [comment]
Fixed in 6d21738 by lowercasing directory name.

**Comment by Genaker** [comment]
Thank! Awesome module!

**Comment by Genaker** [comment]
I'm also thinking root folder has name of region. Maybe it is better to name it by VPC name?

**Comment by antonbabenko** [comment]
No, resources are grouped according to public cloud provider model (AWS account => region (or global) => resource)
