### ISSUE TITLE
terragrunt init failed

### ISSUE THREAD

**Issue by louiekwan** [antonbabenko/modules.tf-lambda#36]
## Describe the bug
Using git bash in  Windows machine and try to do terragrunt init

## Expected behavior
It should not fail but get the following, 

provider "aws": failed to create .terraform\plugins\windows_amd64\terraform-provider-aws_v2.57.0_x4.exe: open .terraform\plugins\windows_amd64\terraform-provider-aws_v2.57.0_x4.exe: The system cannot find the path specified..

PLUGIN cahce dir defined as:
TF_PLUGIN_CACHE_DIR=c:/Users/louie.kwan/.terraform.d/plugin-cache

## Actual behavior
2020/04/14 22:16:57 [DEBUG] installing aws 2.57.0 to .terraform\plugins\windows_amd64\terraform-provider-aws_v2.57.0_x4.exe from local cache c:\Users\louie.kwan\.terraform.d\plugin-cache\windows_amd64\terraform-provider-aws_v2.57.0_x4.exe

Error installing provider "aws": failed to create .terraform\plugins\windows_amd64\terraform-provider-aws_v2.57.0_x4.exe: open .terraform\plugins\windows_amd64\terraform-provider-aws_v2.57.0_x4.exe: The system cannot find the path specified..

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occurred.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/windows_amd64

Error: failed to create .terraform\plugins\windows_amd64\terraform-provider-aws_v2.57.0_x4.exe: open .terraform\plugins\windows_amd64\terraform-provider-aws_v2.57.0_x4.exe: The system cannot find the path specified.

## Additional context

Any help is much appreciated.

**Comment by antonbabenko** [comment]
This error does not seem to be related to `modules.tf` project. Please ask Terraform usage related questions in https://discuss.hashicorp.com/ . I am not a Windows expert and can't help with this, sorry.

Closing this issue.
