### ISSUE TITLE
How to make all this more extendable?

### ISSUE THREAD

**Issue by antonbabenko** [antonbabenko/modules.tf-lambda#4]
Thanks for spending your time helping with the reviewal of Python code in this project!

`handler.py` has function `handler` which is invoked by AWS Lambda via API Gateway. 

Currently this project implements:
- [x] convert Cloudcraft json blueprint into modules.tf-schema
- [x] convert modules.tf-schema into Terragrunt code

I am working on adding support for extension or ways to expand this project, for example:
- [ ] convert modules.tf-schema into Terraform code (in addition to Terragrunt)
- [ ] support other formats as inputs (now only Cloudcraft json is supported)

While doing this I feel that I can do it and will spend a lot of time, so I am looking for some advice/help (in no specific order):
1. `handler` now has a linear flow, but it will not be so always. How can I split `handler.py` into several smaller files and include them conditionally (eg, `generate/terraform.py` and `generate/terragrunt.py`) instead of calling `render_terraform_from_modulestf_config` or `render_terragrunt_from_modulestf_config`? Does it make sense to add OOP / Proxy pattern, or is there another more pythoniс way?
1. Does it make sense to split `handler.py` into several smaller files at this point? Now the function `generate_modulestf_config` implements a single interface (Cloudcraft), but I want it to implement different also, and have smaller files.
1. How would you recommend to test this? I do run this with different arguments, but it is not automated more than that.

Please think about this and try to give me an advice for so called "the lowest hanging fruit".

Thank you!

**Comment by Ashald** [comment]
Let me know if you want me to make another pass.
