### ISSUE TITLE
Transformer modules Git clone issue 

### ISSUE THREAD

**Issue by Genaker** [antonbabenko/modules.tf-lambda#41]
The current implementation needs to add SSH_Keys to the Git. It is additional configuration.

Change of all source properties in .hcl files
from:
```
terraform {
source = "git::git@github.com:terraform-aws-modules/terraform-aws-autoscaling.git?ref=v3.4.0"
to:
source = "git::https://github.com/terraform-aws-modules/terraform-aws-autoscaling.git?ref=v3.4.0"
}
```
fixes this problem

Maybe it is possible to use https as the default git method?

**Comment by antonbabenko** [comment]
git+ssh is used because it works for both public and private repositories.

Closing this issue.

**Comment by Genaker** [comment]
Ok, sound good
