### ISSUE TITLE
Terraform code export menu item unavailable

### ISSUE THREAD

**Issue by ablekh** [antonbabenko/modules.tf-lambda#50]
For some reason, the Terraform code menu item in Cloudcraft (free account) is unavailable / greyed out for me. Any ideas about why that might be the case?

**Comment by antonbabenko** [comment]
Hi @ablekh !

Thanks for opening this issue. There was a bug in cloudcraft UI which has been just fixed. Please try again.

**Comment by ablekh** [comment]
Hi @antonbabenko, thank you for clarification. Yes, it works now. Keep up your nice work and best wishes!
