### ISSUE TITLE
Implement the same using https://plantuml.com/

### ISSUE THREAD

**Issue by distributev** [antonbabenko/modules.tf-lambda#61]
For instance using 

https://github.com/awslabs/aws-icons-for-plantuml

## Describe the solution you'd like

You could do 2 ways

  1. From existing AWS infrastructure to a diagram
  2. From an existing diagram to a corresponding AWS terraform script

You could consider other open source modelling tools like 

https://c4model.com/ (which also integrates with plantuml)
https://www.archimatetool.com/

or 

https://mermaid-js.github.io/mermaid/#/

## Describe alternatives you've considered

Your existing solution however I believe it is better to have this built using open source tools.

## Additional context

https://structurizr.com/

https://www.archimatetool.com/resources/

https://engineering.linecorp.com/en/blog/diagramming-software-architecture-using-c4-model-and-c4-plantuml/

Cloud architecture diagrams - C4 model | Simon Brown (3mins)
https://www.youtube.com/watch?v=ALuL9uKqWU4

Visualising software architecture with the C4 model - Simon Brown, Agile on the Beach 2019 (35 mins)
https://www.youtube.com/watch?v=x2-rSnhpw0g

**Similar existing tools**

https://github.com/GoogleCloudPlatform/terraformer
CLI tool to generate terraform files from existing infrastructure (reverse Terraform). Infrastructure to Code
                
https://github.com/dtan4/terraforming
Export existing AWS resources to Terraform style (tf, tfstate)
                
https://former2.com/
https://github.com/iann0036/former2
Generate CloudFormation / Terraform / Troposphere templates from your existing AWS resources.

**Comment by antonbabenko** [comment]
Thanks for opening this issue but I don't think I am going to work on this because I don't have enough incentive and paying customers to spend time on this.

I will consider taking another look at C4 in the future.
