### ISSUE TITLE
S3 bucket name error

### ISSUE THREAD

**Issue by Genaker** [antonbabenko/modules.tf-lambda#63]
## Describe the bug
```
aws_s3_bucket.this[0]: Creating...
╷
│ Error: Error validating S3 bucket name: only lowercase alphanumeric characters and hyphens allowed in "s3_bucket_deployments"
│ 
│   with aws_s3_bucket.this[0],

```

**Comment by antonbabenko** [comment]
You just need to set a valid name for the bucket.

**Comment by Genaker** [comment]
Correct, but module terraform can generate correct name based on the
user/CloudCraft wrong input.

I have fixed all that issues in my files. But it can potentially improve
modules.tf.

I will try create PR.

**Comment by antonbabenko** [comment]
It is rather impossible to try to match requirements by AWS with user's input. Some of the examples:
- SG name should not start with `sg-`
- S3 bucket name should contain only lowercase alphanumeric characters and hyphens
- ...

Instead, we require developers to verify/edit and fix the errors.

Maybe we will improve this in the future but not in the near future.

**Comment by Genaker** [comment]
I will try contribute this fix as an regexp.

We need just replace matches with - and make lower case after, also trim
multiple-.

Security group:

import re regex = r"^sg-" test_str = "sg-my-security" result =
re.sub(regex, “”, test_str).lower()

Something like this.

**Comment by Genaker** [comment]
I see what the issue. there no real way to change/check the Names because it is Just JSON Mapping...
