### ISSUE TITLE
filter_criteria with SQS 

### ISSUE THREAD

**Issue by narayanaitrecruiter** [antonbabenko/modules.tf-lambda#67]
## Describe the bug
We are trying to add a Filter_criteria to the lambda function and did not get code anywhere. we tried our own and it is showing syntax error or some other.  Could you please help me with some examples?

## Actual behavior
A clear and concise description of what has happened.

**Comment by antonbabenko** [comment]
Hi! I am pretty sure you opened an issue in the wrong repository.

**Comment by narayanaitrecruiter** [comment]
Hi Anton, we are trying to implement lambda resource which is connected to SQS. There is filter criteria in the function. Could you please help me with how to code that?

**Comment by antonbabenko** [comment]
I can't help you. Please ask on a better forum. For example, https://discuss.hashicorp.com
