### ISSUE TITLE
Steps from README section "How can I try this?" doesn't work.

### ISSUE THREAD

**Issue by HamletHakobyan** [antonbabenko/modules.tf-lambda#68]
## Describe the bug
The "How can I try this?" steps doesn't work.

## Expected behavior
After fulfilling steps from "How can I try this?" section in readme, I should see Export/Terraform code export button.

## Actual behavior
No "Export/Terraform code export" button on UI.

**Comment by antonbabenko** [comment]
This functionality has been deactivated on the CloudCraft side a while ago.

**Comment by HamletHakobyan** [comment]
Ok, what about fixing readme?
